/- Current EINT submission manuscript axiom audit. -/

import VerificationAsymmetry.TheoremMap

-- Cat 2 textbook inputs allowed by the paper.
#print axioms VerificationAsymmetry.Economy.axiom_ces_wage_ratio
#print axioms VerificationAsymmetry.Economy.axiom_cobb_douglas_factor_share

-- Theorem 9.
#print axioms VerificationAsymmetry.Economy.G_tendsto_at_one
#print axioms VerificationAsymmetry.Economy.G_rpow_tendsto_at_one
#print axioms VerificationAsymmetry.Economy.G_rpow_endpoint_pos
#print axioms VerificationAsymmetry.Economy.wageRatio_eq_ces_marginal_product_ratio
#print axioms VerificationAsymmetry.Economy.thm_inversion_wage_ratio_monotone
#print axioms VerificationAsymmetry.Economy.thm_inversion_wage_ratio_strict
#print axioms VerificationAsymmetry.Economy.thetaInvInf_eq_thetaInv
#print axioms VerificationAsymmetry.Economy.thetaInvMarginalProductInf_eq_thetaInv
#print axioms VerificationAsymmetry.Economy.wageRatioAtCapacity_tendsto_atTop
#print axioms VerificationAsymmetry.Economy.thm_inversion_threshold_closed_form
#print axioms VerificationAsymmetry.Economy.thm_inversion_threshold_in_unit_interval
#print axioms VerificationAsymmetry.Economy.Gstar_strict_in_rBar
#print axioms VerificationAsymmetry.Economy.thm_inversion_threshold_strict_in_rBar
#print axioms VerificationAsymmetry.Economy.thetaInvAtCapacity_antitone
#print axioms VerificationAsymmetry.Economy.thetaInvAtCapacity_strictAnti
#print axioms VerificationAsymmetry.Economy.thetaInvAtCapacity_tendsto_zero
#print axioms VerificationAsymmetry.Economy.thetaInvAtCapacity_tendsto_zero_right

-- Theorem 10 and Proposition 11.
#print axioms VerificationAsymmetry.Economy.cumulativeExperience_const
#print axioms VerificationAsymmetry.Economy.timeIndexedStock_eq_cohort_integral
#print axioms VerificationAsymmetry.Economy.timeIndexedStock_const_eq_Vinf
#print axioms VerificationAsymmetry.Economy.verificationAsymmetryDiagnostic_of_V2
#print axioms VerificationAsymmetry.Economy.cumulativeExperience_step_eq_stepExperience
#print axioms VerificationAsymmetry.Economy.cStar_mem_open_interval
#print axioms VerificationAsymmetry.Economy.stepExperience_ge_tauStar_iff
#print axioms VerificationAsymmetry.Economy.gHard_stepExperience_eq_one_iff
#print axioms VerificationAsymmetry.Economy.exactStepStock_eq_cohort_integral
#print axioms VerificationAsymmetry.Economy.timeIndexedStock_step_eq_exactStepStock
#print axioms VerificationAsymmetry.Economy.preStepStockIntegral_eq_linear
#print axioms VerificationAsymmetry.Economy.preStepStockIntegral_zero_after_Ts
#print axioms VerificationAsymmetry.Economy.preStepStockIntegral_eq_transientStock
#print axioms VerificationAsymmetry.Economy.exactStepStock_zero_after_last_straddle
#print axioms VerificationAsymmetry.Economy.prop_smooth_collapse_above
#print axioms VerificationAsymmetry.Economy.hasDerivAt_hard_stock_below
#print axioms VerificationAsymmetry.Economy.hardStockSlopeBelow_neg
#print axioms VerificationAsymmetry.Economy.VinfHard_tendsto_left_at_thetaStar
#print axioms VerificationAsymmetry.Economy.VinfHard_tendsto_right_zero_at_thetaStar
#print axioms VerificationAsymmetry.Economy.hasDerivAt_smooth_stock_below_at_threshold
#print axioms VerificationAsymmetry.Economy.hasDerivAt_smooth_stock_above_at_threshold
#print axioms VerificationAsymmetry.Economy.hasDerivWithinAt_smoothStock_left
#print axioms VerificationAsymmetry.Economy.hasDerivWithinAt_smoothStock_right
#print axioms VerificationAsymmetry.Economy.prop_smooth_collapse_kink

-- Theorem 13.
#print axioms VerificationAsymmetry.Economy.thm_externality_residual_identity
#print axioms VerificationAsymmetry.Economy.thm_externality_wedge_identity
#print axioms VerificationAsymmetry.Economy.intervalIntegral_exp_neg_eq_LambdaJ
#print axioms VerificationAsymmetry.Economy.intervalIntegral_exp_neg_eq_Lambda
#print axioms VerificationAsymmetry.Economy.wedge_eq_wedgeExplicit
#print axioms VerificationAsymmetry.Economy.hardPromotion_externalityResidual_zero_above
#print axioms VerificationAsymmetry.Economy.hardPromotion_wedge_zero_above
#print axioms VerificationAsymmetry.Economy.wedgeExplicit_monotone
#print axioms VerificationAsymmetry.Economy.smoothWedgePower_tendsto_atTop
#print axioms VerificationAsymmetry.Economy.smoothWedgePower_tendsto_zero
#print axioms VerificationAsymmetry.Economy.smoothPaperWedge_eq_closedForm
#print axioms VerificationAsymmetry.Economy.smoothPaperWedge_tendsto_atTop
#print axioms VerificationAsymmetry.Economy.smoothPaperWedge_tendsto_endpoint
#print axioms VerificationAsymmetry.Economy.smoothPaperWedge_tendsto_zero
#print axioms VerificationAsymmetry.Economy.smoothMarginalProductWedge_tendsto_atTop
#print axioms VerificationAsymmetry.Economy.smoothMarginalProductWedge_tendsto_endpoint
#print axioms VerificationAsymmetry.Economy.smoothMarginalProductWedge_tendsto_zero
#print axioms VerificationAsymmetry.Economy.thm_externality_pigouvian_cobb_douglas_from_axioms

-- Proposition 14.
#print axioms VerificationAsymmetry.Economy.thm_aggregation_cobb_douglas_zero
#print axioms VerificationAsymmetry.Economy.prop_aggregation_fixed_sigma_positive
#print axioms VerificationAsymmetry.Economy.prop_aggregation_near_cobb_douglas_limit

-- Strict one-declaration-per-fragment bindings.
#print axioms VerificationAsymmetry.Economy.paper_definition1_parameters_exact
#print axioms VerificationAsymmetry.Economy.paper_equation1_ces_exact
#print axioms VerificationAsymmetry.Economy.paper_definition3_generation_supply_exact
#print axioms VerificationAsymmetry.Economy.paper_equation2_generation_supply_exact
#print axioms VerificationAsymmetry.Economy.paper_definition4_cohort_dynamics_exact
#print axioms VerificationAsymmetry.Economy.paper_equation3_cumulative_experience_exact
#print axioms VerificationAsymmetry.Economy.paper_assumption6_time_indexed_stock_exact
#print axioms VerificationAsymmetry.Economy.paper_lemma7_steady_state_stock_exact
#print axioms VerificationAsymmetry.Economy.paper_equation4_steady_state_stock_exact
#print axioms VerificationAsymmetry.Economy.paper_equation5_hard_stock_exact
#print axioms VerificationAsymmetry.Economy.paper_equation6_smooth_stock_exact
#print axioms VerificationAsymmetry.Economy.paper_definition8_diagnostic_exact
#print axioms VerificationAsymmetry.Economy.paper_theorem9_inversion_exact
#print axioms VerificationAsymmetry.Economy.paper_equation7_wage_ratio_exact
#print axioms VerificationAsymmetry.Economy.paper_equation8_inversion_threshold_exact
#print axioms VerificationAsymmetry.Economy.paper_theorem10_pipeline_collapse_exact
#print axioms VerificationAsymmetry.Economy.paper_equation9_collapse_threshold_exact
#print axioms VerificationAsymmetry.Economy.paper_equation10_transient_stock_exact
#print axioms VerificationAsymmetry.Economy.paper_proposition11_smooth_collapse_exact
#print axioms VerificationAsymmetry.Economy.paper_equation11_smooth_stock_exact
#print axioms VerificationAsymmetry.Economy.paper_theorem13_externality_exact
#print axioms VerificationAsymmetry.Economy.paper_equation12_social_present_value_exact
#print axioms VerificationAsymmetry.Economy.paper_equation13_apprenticeship_wedge_exact
#print axioms VerificationAsymmetry.Economy.paper_equation14_explicit_wedge_exact
#print axioms VerificationAsymmetry.Economy.paper_theorem13_partial_capture_atomic
#print axioms VerificationAsymmetry.Economy.paper_proposition14_aggregation_exact
#print axioms VerificationAsymmetry.Economy.paper_equation15_aggregate_output_exact
